version: '3.3'
services:
  incorgnito:
    image: zate75/incorgnito:latest
    command: /incorgnito
    networks:
     - default
    logging:
      driver: json-file
    volumes: 
      - ./ChannelList.json:/ChannelList.json
    environment:
      - BOT_TOKEN
    deploy:
      placement:
        constraints:
          - node.role == manager
          
networks:
  default:
    driver: overlay