version: '3'
services:
  incorgnito:
    build:
      context: .
    image: "zate75/incorgnito:latest"
    container_name: incorgnito
    command: /incorgnito
    volumes: 
      - channelList:/ChannelList.json
    environment: 
      - BOT_TOKEN
    restart: always

volumes:
  channelList:
    external: true