version: '3'
services:
  incorgnito:
    build:
      context: .
    image: "zate75/ingorgnito:latest"
    container_name: incorgnito
    command: /incorgnito
    volumes: 
      - ./ChannelList.json:/ChannelList.json
    environment: 
      - BOT_TOKEN
    restart: always